env:
  es2021: true
  node: true
extends: 
  - '@typescript-eslint/recommended'
  - 'airbnb-base'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
  - 'import'
rules:
  'callback-return': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-unsafe-assignment': 'off'
  '@typescript-eslint/no-unsafe-member-access': 'off'
  '@typescript-eslint/no-unsafe-call': 'off'
  '@typescript-eslint/no-unsafe-return': 'off'
  '@typescript-eslint/ban-ts-comment': 'off'
  'import/extensions': 
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  'import/no-unresolved': 'off'
  'import/prefer-default-export': 'off'
  'class-methods-use-this': 'off'
  'no-underscore-dangle': 'off'
settings:
  import/resolver:
    typescript: {}